version: 1
disable_existing_loggers: true
# Configuring the default (root) logger is highly recommended
root:
    level: INFO
    handlers: [console]
loggers:
    # Logging from my application
    # Controlling logging of 3rd party libs
    sqlalchemy.engine:
      level: !!python/name:logging.WARN
      handlers: [logfile,console]
      qualname: sqlalchemy.engine
      propagate: false
    sqlalchemy.pool:
      level: !!python/name:logging.WARN
      handlers: [logfile]
      qualname: sqlalchemy.pool
      propagate: false
    requests.packages.urllib3.connectionpool:
      level: !!python/name:logging.WARN
      handlers: [console]
      qualname: requests.packages.urllib3.connectionpool
      propagate: false
handlers:
    logfile:
      class: logging.FileHandler
      filename: sample.log
      formatter: simpleFormatter
      level: !!python/name:logging.NOTSET
    console:
      class: logging.StreamHandler
      stream: ext://sys.stderr
      formatter: simpleFormatter
      level: !!python/name:logging.NOTSET
formatters:
    simpleFormatter:
      class: !!python/name:logging.Formatter
      format: "%(asctime)s - %(levelname)s - %(name)s:%(lineno)d  - %(message)s"
      datefmt: "%Y-%m-%dT%H:%M:%S"
